### ISSUE TITLE
training on KITTI

### ISSUE THREAD

**Issue by 00ohnim** [ClementPinard/FlowNetPytorch#122]
Hi,thanks for your project!However,when I run it on KITTI,it broke with an issue

Traceback (most recent call last):
  File "main.py", line 454, in <module>
    main()
  File "main.py", line 236, in main
    train_set, test_set = datasets.__dict__[args.dataset](
TypeError: 'module' object is not callable

Does it mean I need to split the dataset?
I use the code to train :python main.py /home/xu/wyh/dataset/KITTI  -b8 -j8 -a flownets

Thanks for your help!!!!

**Comment by ClementPinard** [comment]
Hi, could run the script without any problem, on python 3.12 and torch v2.4.
Did you change something in the script or in the folder structure ? Looks like a function was overwritten by a module somehow.

Also, if you plan on training for KITTI, you will need to select the `--dataset` option, otherwise it will expect a dataset with the same format as Flying chairs.

```python
python main.py /home/xu/wyh/dataset/KITTI -b8 -j8 -a flownets --dataset KITTI_occ
```
