### ISSUE TITLE
error in flow2rgb, flow_map_np.shape

### ISSUE THREAD

**Issue by SRSH88** [ClementPinard/FlowNetPytorch#66]
Thanks for sharing your code
I got the following error when running the run_inference.py on a pair of images from KITTI dataset. 
I tried to remove the "_," from the line 37, but the PNG output was not correct.
I am using: cuda 9.2, pytorch 1.0.1, python 3.6.2,  spatial-correlation-sampler 0.1.0

```
=> will save raw output and RGB visualization
=> fetching img pairs in './myImg/'
=> will save everything to ./myImg/flow
1 samples found
=> using pre-trained model 'flownetc'
  0%|                                                                              | 0/1 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "run_inference.py", line 118, in <module>
    main()
  File "/home/ems/anaconda3/envs/clmt/lib/python3.6/site-packages/torch/autograd/grad_mode.py", line 43, in decorate_no_grad
    return func(*args, **kwargs)
  File "run_inference.py", line 108, in main
    rgb_flow = flow2rgb(args.div_flow * flow_output[0], max_value=args.max_flow)
  File "/media/ems/DATA/Soroush/Flownet/Clement/FlowNetPytorch/util.py", line 37, in flow2rgb
    _, h, w = flow_map_np.shape
ValueError: not enough values to unpack (expected 3, got 2)
```

**Comment by ClementPinard** [comment]
Hello,

I suspect the problem is line 108
` rgb_flow = flow2rgb(args.div_flow * flow_output[0], max_value=args.max_flow)` 

can you remove the `[0]` from `flow_output[0]` and see how it works for you ?

**Comment by SRSH88** [comment]
Thanks,
It solved the problem. Nice result.
