### ISSUE TITLE
issue of running inference

### ISSUE THREAD

**Issue by Naturallyyeyeye** [ClementPinard/FlowNetPytorch#79]
Hi, I would like to ask for a help,I meet the problem as follows:
 Traceback (most recent call last):
  File "/home/yjj/Downloads/FlowNetPytorch-master/run_inference.py", line 121, in <module>
  main()
  File "/home/yjj/.conda/envs/FlowNetPytorch/lib/python3.6/site-packages/torch/autograd/grad_mode.py", line 49, in decorate_no_grad
    return func(*args, **kwargs)
  File "/home/yjj/Downloads/FlowNetPytorch-master/run_inference.py", line 83, in main
    network_data = torch.load(args.pretrained)
  File "/home/yjj/.conda/envs/FlowNetPytorch/lib/python3.6/site-packages/torch/serialization.py", line 426, in load
    return _load(f, map_location, pickle_module, **pickle_load_args)
  File "/home/yjj/.conda/envs/FlowNetPytorch/lib/python3.6/site-packages/torch/serialization.py", line 603, in _load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: could not find MARK

**Comment by ClementPinard** [comment]
What pytorch version are you using, and what file are you using to load the network?
