### ISSUE TITLE
PIL cannot handle this data type

### ISSUE THREAD

**Issue by gemenerik** [ClementPinard/FlowNetPytorch#93]
After a full epoch the following error occurs in the `flow2rgb` util function. After commenting out both uses (GroundTruth and FlowNet Outputs being added to `output_writers` in `main.py`), everything runs well.

```
Traceback (most recent call last):
  File "/home/rik/miniconda3/envs/pytorch/lib/python3.8/site-packages/PIL/Image.py", line 2751, in fromarray
    mode, rawmode = _fromarray_typemap[typekey]
KeyError: ((1, 1, 512), '|u1')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "main.py", line 314, in <module>
    main()
  File "main.py", line 200, in main
    EPE = validate(val_loader, model, epoch, output_writers)
  File "main.py", line 299, in validate
    output_writers[i].add_image('GroundTruth', flow2rgb(args.div_flow * target[0], max_value=10), 0)
  File "/home/rik/miniconda3/envs/pytorch/lib/python3.8/site-packages/tensorboardX/writer.py", line 277, in add_image
    self.file_writer.add_summary(image(tag, img_tensor), global_step)
  File "/home/rik/miniconda3/envs/pytorch/lib/python3.8/site-packages/tensorboardX/summary.py", line 166, in image
    image = make_image(tensor)
  File "/home/rik/miniconda3/envs/pytorch/lib/python3.8/site-packages/tensorboardX/summary.py", line 173, in make_image
    image = Image.fromarray(tensor)
  File "/home/rik/miniconda3/envs/pytorch/lib/python3.8/site-packages/PIL/Image.py", line 2753, in fromarray
    raise TypeError("Cannot handle this data type: %s, %s" % typekey) from e
TypeError: Cannot handle this data type: (1, 1, 512), |u1
```

Thanks for keeping this repo updated.

**Comment by ClementPinard** [comment]
Hi, just tested this code on FlyingChairs with Pytorch 1.7 and ubuntu 20, and I have no problem. What is your system, and what dataset are you using  ?

**Comment by gemenerik** [comment]
I think something went wrong with installing requirements, I just tried a fresh clone and it works just fine. Was running the same system, dataset.
